import { User, Product, Order, Notification, ActivityEvent, CalendarEvent } from './types';

// Seed Users
export const initialUsers: User[] = [
  {
    id: 'USR-101',
    name: 'Sarah Jenkins',
    email: 'sarah.j@enterprise.io',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    role: 'Administrator',
    status: 'Active',
    lastActive: '5 mins ago',
    location: 'San Francisco, CA',
    joinDate: '2024-01-15',
  },
  {
    id: 'USR-102',
    name: 'Michael Chen',
    email: 'm.chen@enterprise.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    role: 'Editor',
    status: 'Active',
    lastActive: '12 mins ago',
    location: 'Vancouver, BC',
    joinDate: '2024-02-10',
  },
  {
    id: 'USR-103',
    name: 'Amara Okafor',
    email: 'amara.o@enterprise.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    role: 'Support Agent',
    status: 'Active',
    lastActive: '1 hour ago',
    location: 'London, UK',
    joinDate: '2024-03-01',
  },
  {
    id: 'USR-104',
    name: 'David Miller',
    email: 'david.m@external-developer.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    role: 'User',
    status: 'Inactive',
    lastActive: '3 days ago',
    location: 'Austin, TX',
    joinDate: '2024-04-14',
  },
  {
    id: 'USR-105',
    name: 'Elena Rostova',
    email: 'elena.r@enterprise.io',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    role: 'Editor',
    status: 'Active',
    lastActive: 'Just now',
    location: 'Tallinn, Estonia',
    joinDate: '2024-01-20',
  },
  {
    id: 'USR-106',
    name: 'Marcus Vance',
    email: 'marcus.v@partner-supply.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    role: 'User',
    status: 'Suspended',
    lastActive: '2 weeks ago',
    location: 'Chicago, IL',
    joinDate: '2024-05-11',
  },
  {
    id: 'USR-107',
    name: 'Chloe Kim',
    email: 'chloe.k@enterprise.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    role: 'Support Agent',
    status: 'Active',
    lastActive: '30 mins ago',
    location: 'Seoul, SK',
    joinDate: '2024-03-15',
  },
];

// Seed Products
export const initialProducts: Product[] = [
  {
    id: 'PROD-301',
    name: 'Quantum Core Supercomputing Server',
    sku: 'QC-SRV-901',
    category: 'Hardware',
    stock: 14,
    price: 12499.0,
    status: 'In Stock',
    ordersCount: 42,
    rating: 4.9,
  },
  {
    id: 'PROD-302',
    name: 'Neural Engine SDK Licensing [Enterprise]',
    sku: 'NE-SDK-ENT',
    category: 'Software License',
    stock: 500,
    price: 3500.0,
    status: 'In Stock',
    ordersCount: 110,
    rating: 4.8,
  },
  {
    id: 'PROD-303',
    name: 'Helix Biometric Security Gateway',
    sku: 'HLX-SEC-BIO',
    category: 'Security Devices',
    stock: 4,
    price: 899.00,
    status: 'Low Stock',
    ordersCount: 95,
    rating: 4.7,
  },
  {
    id: 'PROD-304',
    name: 'Apex Analytics Dashboard Hub [V4]',
    sku: 'APX-DBH-V4',
    category: 'Software License',
    stock: 120,
    price: 1500.00,
    status: 'In Stock',
    ordersCount: 230,
    rating: 4.9,
  },
  {
    id: 'PROD-305',
    name: 'Optic Fiber Array Transceiver 100G',
    sku: 'OPT-TX-100G',
    category: 'Networking',
    stock: 0,
    price: 420.00,
    status: 'Out of Stock',
    ordersCount: 64,
    rating: 4.5,
  },
  {
    id: 'PROD-306',
    name: 'Synapse IoT Node Controller',
    sku: 'SYN-IOT-NOD',
    category: 'Hardware',
    stock: 8,
    price: 249.50,
    status: 'Low Stock',
    ordersCount: 154,
    rating: 4.2,
  },
  {
    id: 'PROD-307',
    name: 'Zero-Trust Protocol Proxy Key',
    sku: 'ZT-PRX-KEY',
    category: 'Security Devices',
    stock: 125,
    price: 89.99,
    status: 'In Stock',
    ordersCount: 1240,
    rating: 4.6,
  },
];

// Seed Orders
export const initialOrders: Order[] = [
  {
    id: 'ORD-7589',
    customerName: 'Astra Biotech Inc.',
    email: 'procurement@astrabio.com',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150',
    date: '2026-05-24',
    amount: 28498.00,
    status: 'Delivered',
    shippingAddress: '480 Innovation Way, Bldg D, Boston, MA 02110',
    paymentMethod: 'Bank Wire Transfer',
    items: [
      { id: '1', productName: 'Quantum Core Supercomputing Server', qty: 2, price: 12499.00 },
      { id: '2', productName: 'Neural Engine SDK Licensing [Enterprise]', qty: 1, price: 3500.00 },
    ],
  },
  {
    id: 'ORD-7590',
    customerName: 'Cyberdyne Systems',
    email: 't800@cyberdyneresearch.la',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
    date: '2026-05-24',
    amount: 7000.00,
    status: 'Processing',
    shippingAddress: '101 Cyberdyne Blvd, Sector 7, Los Angeles, CA 90025',
    paymentMethod: 'Corporate Credit Card',
    items: [
      { id: '1', productName: 'Neural Engine SDK Licensing [Enterprise]', qty: 2, price: 3500.00 },
    ],
  },
  {
    id: 'ORD-7591',
    customerName: 'Kuroshio Network',
    email: 'ops@kuroshio.jp',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    date: '2026-05-25',
    amount: 1798.00,
    status: 'Pending',
    shippingAddress: 'Shibuya Crossing-Tower B, Fl 28, Tokyo, Japan',
    paymentMethod: 'Purchase Order Auth',
    items: [
      { id: '1', productName: 'Helix Biometric Security Gateway', qty: 2, price: 899.00 },
    ],
  },
  {
    id: 'ORD-7592',
    customerName: 'Genesis Web Ventures',
    email: 'billing@genesisweb.co',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    date: '2026-05-23',
    amount: 4500.00,
    status: 'Delivered',
    shippingAddress: '18 West 21st St, Suite 4A, New York, NY 10010',
    paymentMethod: 'Stripe Corporate Route',
    items: [
      { id: '1', productName: 'Apex Analytics Dashboard Hub [V4]', qty: 3, price: 1500.00 },
    ],
  },
  {
    id: 'ORD-7593',
    customerName: 'Vanguard Integrators',
    email: 'supplier@vanguard-ops.net',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    date: '2026-05-22',
    amount: 1260.00,
    status: 'Cancelled',
    shippingAddress: '89 Logistics Loop, Dock 12, Chicago, IL 60611',
    paymentMethod: 'Direct Debit API',
    items: [
      { id: '1', productName: 'Optic Fiber Array Transceiver 100G', qty: 3, price: 420.00 },
    ],
  },
  {
    id: 'ORD-7594',
    customerName: 'Summit Technical Labs',
    email: 'info@summitlabs.nz',
    avatar: 'https://images.unsplash.com/photo-1511551201822-ed7f2e40f10c?w=150',
    date: '2026-05-25',
    amount: 2249.50,
    status: 'Processing',
    shippingAddress: '32 Alpine Peaks Dr, Queenstown, New Zealand',
    paymentMethod: 'Corporate ACH',
    items: [
      { id: '1', productName: 'Helix Biometric Security Gateway', qty: 1, price: 899.00 },
      { id: '2', productName: 'Synapse IoT Node Controller', qty: 5, price: 249.50 },
      { id: '3', productName: 'Zero-Trust Protocol Proxy Key', qty: 1, price: 89.99 },
    ],
  },
];

// Seed Alerts
export const initialNotifications: Notification[] = [
  {
    id: 'NOT-1001',
    type: 'warning',
    category: 'audit',
    message: 'Low stock on security key hardware',
    description: 'Helix Biometric Security Gateway stock count is down to 4 units remaining. Please submit reorder trigger.',
    timestamp: '23 mins ago',
    read: false,
  },
  {
    id: 'NOT-1002',
    type: 'success',
    category: 'billing',
    message: 'Enterprise Invoice Paid',
    description: 'Astra Biotech Inc. has successfully processed Wire Transfer reference ID #WT-28498 for a value of $28,498.00.',
    timestamp: '1 hour ago',
    read: false,
  },
  {
    id: 'NOT-1003',
    type: 'error',
    category: 'security',
    message: 'Unauthorized Root Access Attempt',
    description: 'Security firewall blocked an attempted SSH root access from IP range 182.16.2.221 targeting application databases.',
    timestamp: '3 hours ago',
    read: false,
  },
  {
    id: 'NOT-1004',
    type: 'info',
    category: 'general',
    message: 'Node Orchestration System Upgrade',
    description: 'Kubernetes ingress controller successfully upgraded to core v1.30.2. Service load balancer checks passed.',
    timestamp: '1 day ago',
    read: true,
  },
  {
    id: 'NOT-1005',
    type: 'warning',
    category: 'audit',
    message: 'Inactive Editor Account Warning',
    description: 'User "Elena Rostova" editor permissions warning: last action was logged more than 45 days ago. Auto-review pending.',
    timestamp: '2 days ago',
    read: true,
  },
];

// Seed Activity Timeline
export const initialActivityEvents: ActivityEvent[] = [
  {
    id: 'ACT-901',
    user: 'Sarah Jenkins',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    action: 'Modified security permission rules',
    detail: 'Downgraded client scope role definitions for external contractors to "User" role default restrict.',
    type: 'warning',
    time: '23 mins ago',
  },
  {
    id: 'ACT-902',
    user: 'Michael Chen',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    action: 'Updated inventory specs',
    detail: 'Modified retail pricing parameters for Neural Engine SDK Licensing [Enterprise] packages for Q3 marketing campaigns.',
    type: 'info',
    time: '45 mins ago',
  },
  {
    id: 'ACT-903',
    user: 'Amara Okafor',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    action: 'Resolved customer ticket #7911',
    detail: 'Customer login loop fix provisioned by resetting cookies gateway for client tenant identifier space.',
    type: 'success',
    time: '2 hours ago',
  },
  {
    id: 'ACT-904',
    user: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    action: 'Created new campaign routing link',
    detail: 'Setup redirect protocols inside Apex Analytics Hub redirecting traffic from developer portals.',
    type: 'success',
    time: '4 hours ago',
  },
  {
    id: 'ACT-905',
    user: 'System Ingress Bot',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150',
    action: 'Automated database cold-backup',
    detail: 'Completed full JSON raw transaction ledger snapshots and encrypted artifacts securely stored in Google Cloud Drive archive bucket SBX-24.',
    type: 'info',
    time: '6 hours ago',
  },
];

// Seed Calendar Events
export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: 'EVT-01',
    title: 'Lead Architect Sync',
    description: 'Infrastructure and database migration strategies layout meeting.',
    date: '2026-05-25',
    startTime: '10:00',
    endTime: '11:30',
    type: 'work',
    color: 'emerald',
  },
  {
    id: 'EVT-02',
    title: 'Q3 Enterprise Sales Strategy review',
    description: 'Coordinate core subscription contracts renewals and pipeline reviews with regional accounts.',
    date: '2026-05-25',
    startTime: '14:00',
    endTime: '15:30',
    type: 'work',
    color: 'blue',
  },
  {
    id: 'EVT-03',
    title: 'Platform Maintenance Window',
    description: 'System-wide failover servers simulation testing and primary storage hot upgrades.',
    date: '2026-05-26',
    startTime: '01:00',
    endTime: '04:00',
    type: 'urgent',
    color: 'rose',
  },
  {
    id: 'EVT-04',
    title: 'Supplier Logistics Pipeline Audit',
    description: 'Address component low-stock alarms with Apex Network hardware providers.',
    date: '2026-05-28',
    startTime: '11:00',
    endTime: '12:30',
    type: 'system',
    color: 'amber',
  },
  {
    id: 'EVT-05',
    title: 'Tech Founders Happy Hour',
    description: 'Networking and ecosystem alignment mixer after general board panels.',
    date: '2026-05-29',
    startTime: '18:00',
    endTime: '21:00',
    type: 'private',
    color: 'violet',
  },
];

// Sparkline series helper coordinates (revenue, signups, sales, conversion)
export const initialStats: DashboardStats = {
  totalRevenue: { value: 247890.50, change: 12.8, series: [180, 210, 195, 240, 220, 230, 247.89] },
  activeUsers: { value: 14820, change: 8.4, series: [12.1, 12.5, 13.0, 13.4, 14.1, 14.3, 14.82] },
  totalSales: { value: 1850, change: -2.3, series: [2.1, 1.9, 2.3, 1.8, 2.0, 1.92, 1.85] },
  conversionRate: { value: 3.42, change: 4.1, series: [3.1, 3.2, 2.9, 3.3, 3.25, 3.38, 3.42] },
};
